// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineStoreMicroservices.DiscountCoupon.Context;

namespace OnlineStoreMicroservices.DiscountCoupon.Migrations
{
    [DbContext(typeof(DiscountCouponDbContext))]
    [Migration("20221009171356_InitialWithSeed")]
    partial class InitialWithSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnlineStoreMicroservices.DiscountCoupon.Models.DiscountCoupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntegrationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActual")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("DiscountCoupons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 10,
                            Code = "ten",
                            IntegrationId = "e0cfebf1-5fa6-49d0-a726-c5c4b2ce3de9",
                            IsActual = true
                        },
                        new
                        {
                            Id = 2,
                            Amount = 20,
                            Code = "twenty",
                            IntegrationId = "3ed3adc6-7416-4d63-9048-9d1b92554c21",
                            IsActual = true
                        },
                        new
                        {
                            Id = 3,
                            Amount = 30,
                            Code = "thirty",
                            IntegrationId = "fd918135-bcf1-4310-8b20-81365ad80862",
                            IsActual = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
